-- Ensure system chat names/descriptions are canonical and readable.
UPDATE chats
SET name = 'Общий чат'
WHERE system_key = 'general'
  AND name <> 'Общий чат';

UPDATE chats
SET name = 'Заметки',
    description = 'Это чат для личных заметок. Здесь удобно хранить:
— планы на день;
— список покупок;
— полезные ссылки;
— мысли и идеи.

Это ваш личный чат, в него нельзя добавлять других людей. Но при желании вы можете пересылать сообщения из заметок в другие чаты.'
WHERE chat_type = 'notes'
  AND (name <> 'Заметки' OR description IS DISTINCT FROM 'Это чат для личных заметок. Здесь удобно хранить:
— планы на день;
— список покупок;
— полезные ссылки;
— мысли и идеи.

Это ваш личный чат, в него нельзя добавлять других людей. Но при желании вы можете пересылать сообщения из заметок в другие чаты.');

-- Repair legacy mojibake system messages generated by old builds.
UPDATE messages m
SET content = 'Добавлен пользователь ' || COALESCE(u.username, 'пользователь')
FROM users u
WHERE u.id = m.sender_id
  AND (
    m.content LIKE 'Ð”>102;5=%'
    OR m.content LIKE 'Ð”Ð¾Ð±Ð°Ð²Ð»ÐµÐ½ Ð¿Ð¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»ÑŒ %'
  );
